### ISSUE TITLE
Error when training the model

### ISSUE THREAD

**Issue by claudehang** [ngeorgis/ca-fire-detector#2]
Hi, I follow the fire-detection-jetson-save-ca.ipynb, and when I run to the line:
```
hist = model.fit(train_tensors, train_targets, batch_size=64, epochs=10,
      validation_data=(valid_tensors, valid_targets), callbacks=[checkpointer, tbCallback],
      verbose=2)  #, shuffle=True)
```
It reports the error as follows:
```
Train on 535 samples, validate on 87 samples
Epoch 1/10
 - 18s - loss: 2.6562 - acc: 0.8299 - val_loss: 2.7790 - val_acc: 0.8276

Epoch 00001: val_loss improved from inf to 2.77898, saving model to firemodel.weights.best.hdf5
Traceback (most recent call last):
  File "keras_fire.py", line 103, in <module>
    verbose=2)
  File "/usr/lib64/python2.7/site-packages/keras/engine/training.py", line 1042, in fit
    validation_steps=validation_steps)
  File "/usr/lib64/python2.7/site-packages/keras/engine/training_arrays.py", line 219, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/lib64/python2.7/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/lib64/python2.7/site-packages/keras/callbacks.py", line 444, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/usr/lib64/python2.7/site-packages/keras/engine/network.py", line 1104, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/usr/lib64/python2.7/site-packages/keras/engine/saving.py", line 122, in save_model
    save_weights_to_hdf5_group(model_weights_group, model_layers)
  File "/usr/lib64/python2.7/site-packages/keras/engine/saving.py", line 457, in save_weights_to_hdf5_group
    save_attributes_to_hdf5_group(g, 'weight_names', weight_names)
  File "/usr/lib64/python2.7/site-packages/keras/engine/saving.py", line 409, in save_attributes_to_hdf5_group
    group.attrs[name] = data
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/lib64/python2.7/site-packages/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/usr/lib64/python2.7/site-packages/h5py/_hl/attrs.py", line 180, in create
    space = h5s.create_simple(shape)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5s.pyx", line 101, in h5py.h5s.create_simple
ValueError: Zero sized dimension for non-unlimited dimension (zero sized dimension for non-unlimited dimension)
```
Could you help me with this error and give me some suggestions? Many thanks!

**Comment by claudehang** [comment]
By the way, I've confirm that my configuration of `h5py` is of quite new version 2.7.1, which should be compatible.

**Comment by ngeorgis** [comment]
Hi @claudehang ,
I cannot repro this. Matybe related to your training dataset (?)

`# load train, test, and validation datasets
train_files, train_targets = load_dataset('fireImages/train')
valid_files, valid_targets = `load_dataset('fireImages/valid')`
test_files, test_targets = load_dataset('fireImages/test')`

Could you share and I can try to repro here.

**Comment by claudehang** [comment]
@ngeorgis Thanks man! I solved this by switching to another version of `h5py` and it works somehow.

**Comment by ngeorgis** [comment]
Great! Glad to hear.
